# -*- coding: utf-8 -*-
"""guessing-game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yehNNHmlyPr21i5jeVvk7yENOx-MRup0
"""

import random
print("Welcome to Zach's guessing game!!")

MIN_VALUE = 1
MAX_VALUE = 10
MAX_TRIES = 3

number = random.randint(MIN_VALUE, MAX_VALUE)
tries = 0

print("I am thinking of a number between {mini} and {maxi}\nCan you guess it?".format(mini=MIN_VALUE, maxi=MAX_VALUE))

while tries < MAX_TRIES:

  guess = int(input())

  if guess == number:
    print("You guessed my number. YOU WIN!!")
    break

  elif guess > number:
    print("Your guess is too large.")

  else:
    print("Your guess is too small.")
    
  tries += 1

if (tries >= MAX_TRIES):
  print("You have used all of your tries. YOU LOSE.")
