# -*- coding: utf-8 -*-
"""guessing-game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yehNNHmlyPr21i5jeVvk7yENOx-MRup0
"""

import random

#DEFINE CONSTANTS
MIN_VALUE = 1
MAX_VALUE = 10
NUM_TRIES = 2

#METHODS
def generate_random_int(min, max):
  return random.randint(min, max)

#GAME INITIATION
val = generate_random_int(MIN_VALUE, MAX_VALUE)
gameOver = False
tries = 0
welcome_msg = """Welcome to the number guessing game. 
I am thinking of a number between {mini} and {maxi}. 
You have {num} tries to guess it. Good luck!!!"""

print(welcome_msg.format(mini=MIN_VALUE, maxi=MAX_VALUE, num=NUM_TRIES))

guess = int(input('Guess a number: '))

#MAIN LOOP
while not gameOver:

  #ARE TRIES UP?
  if (tries >= NUM_TRIES):
    print("Your {num} tries are up. YOU LOSE.".format(num=NUM_TRIES))
    gameOver = True
    break
  
  #CHECK IF GUESS IS CORRECT
  if guess == val:
    print('Congratulations you guessed the number. YOU WIN!!')
    gameOver = True
    break
  else: 
    guess = int(input('Sorry but your guess was incorrect. Try again: '))
  

  #INCREMENT TRIES
  tries += 1